# Generated by Django 5.1.3 on 2025-01-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopimg', models.CharField(max_length=100)),
                ('shopWishlist', models.CharField(max_length=100)),
                ('shopquickview', models.CharField(max_length=50)),
                ('Compare', models.CharField(max_length=50)),
                ('shoptitle', models.CharField(max_length=100)),
                ('shopdes', models.CharField(max_length=100)),
                ('shopprice', models.CharField(max_length=50)),
            ],
        ),
    ]
