# Generated by Django 5.1.3 on 2025-01-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopimg', models.URLField(max_length=255)),
                ('shopWishlist', models.URLField(max_length=255)),
                ('shopquickview', models.URLField(max_length=255)),
                ('Compare', models.URLField(max_length=255)),
                ('shoptitle', models.CharField(max_length=100)),
                ('shopdes', models.CharField(max_length=100)),
                ('shopprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addtocard', models.URLField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
